// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/SamSafonov2025/go-diploma-tpl/internal/models"
	gomock "github.com/golang/mock/gomock"
	sqlx "github.com/jmoiron/sqlx"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockStorage) CreateOrder(ctx context.Context, order models.Order, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, order, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockStorageMockRecorder) CreateOrder(ctx, order, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockStorage)(nil).CreateOrder), ctx, order, tx)
}

// CreateUser mocks base method.
func (m *MockStorage) CreateUser(ctx context.Context, user models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStorageMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStorage)(nil).CreateUser), ctx, user)
}

// CreateWithdrawal mocks base method.
func (m *MockStorage) CreateWithdrawal(ctx context.Context, withdrawal models.Withdrawal, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawal", ctx, withdrawal, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithdrawal indicates an expected call of CreateWithdrawal.
func (mr *MockStorageMockRecorder) CreateWithdrawal(ctx, withdrawal, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawal", reflect.TypeOf((*MockStorage)(nil).CreateWithdrawal), ctx, withdrawal, tx)
}

// ExecuteTransaction mocks base method.
func (m *MockStorage) ExecuteTransaction(ctx context.Context, fn func(context.Context, *sqlx.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteTransaction indicates an expected call of ExecuteTransaction.
func (mr *MockStorageMockRecorder) ExecuteTransaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTransaction", reflect.TypeOf((*MockStorage)(nil).ExecuteTransaction), ctx, fn)
}

// FetchBalanceByUserID mocks base method.
func (m *MockStorage) FetchBalanceByUserID(ctx context.Context, userID string) (models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBalanceByUserID", ctx, userID)
	ret0, _ := ret[0].(models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchBalanceByUserID indicates an expected call of FetchBalanceByUserID.
func (mr *MockStorageMockRecorder) FetchBalanceByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBalanceByUserID", reflect.TypeOf((*MockStorage)(nil).FetchBalanceByUserID), ctx, userID)
}

// FetchCurrentBalance mocks base method.
func (m *MockStorage) FetchCurrentBalance(ctx context.Context, userID string, tx *sqlx.Tx) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCurrentBalance", ctx, userID, tx)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCurrentBalance indicates an expected call of FetchCurrentBalance.
func (mr *MockStorageMockRecorder) FetchCurrentBalance(ctx, userID, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCurrentBalance", reflect.TypeOf((*MockStorage)(nil).FetchCurrentBalance), ctx, userID, tx)
}

// FetchOrdersByUserID mocks base method.
func (m *MockStorage) FetchOrdersByUserID(ctx context.Context, userID string) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOrdersByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOrdersByUserID indicates an expected call of FetchOrdersByUserID.
func (mr *MockStorageMockRecorder) FetchOrdersByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOrdersByUserID", reflect.TypeOf((*MockStorage)(nil).FetchOrdersByUserID), ctx, userID)
}

// FetchPendingOrders mocks base method.
func (m *MockStorage) FetchPendingOrders(ctx context.Context) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPendingOrders", ctx)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPendingOrders indicates an expected call of FetchPendingOrders.
func (mr *MockStorageMockRecorder) FetchPendingOrders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPendingOrders", reflect.TypeOf((*MockStorage)(nil).FetchPendingOrders), ctx)
}

// FetchWithdrawalsByUserID mocks base method.
func (m *MockStorage) FetchWithdrawalsByUserID(ctx context.Context, userID string) ([]models.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWithdrawalsByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWithdrawalsByUserID indicates an expected call of FetchWithdrawalsByUserID.
func (mr *MockStorageMockRecorder) FetchWithdrawalsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWithdrawalsByUserID", reflect.TypeOf((*MockStorage)(nil).FetchWithdrawalsByUserID), ctx, userID)
}

// FindUserByLogin mocks base method.
func (m *MockStorage) FindUserByLogin(ctx context.Context, user models.User) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByLogin", ctx, user)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByLogin indicates an expected call of FindUserByLogin.
func (mr *MockStorageMockRecorder) FindUserByLogin(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByLogin", reflect.TypeOf((*MockStorage)(nil).FindUserByLogin), ctx, user)
}

// IncreaseWithdrawnAmount mocks base method.
func (m *MockStorage) IncreaseWithdrawnAmount(ctx context.Context, userID string, amount float64, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseWithdrawnAmount", ctx, userID, amount, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseWithdrawnAmount indicates an expected call of IncreaseWithdrawnAmount.
func (mr *MockStorageMockRecorder) IncreaseWithdrawnAmount(ctx, userID, amount, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseWithdrawnAmount", reflect.TypeOf((*MockStorage)(nil).IncreaseWithdrawnAmount), ctx, userID, amount, tx)
}

// ModifyOrder mocks base method.
func (m *MockStorage) ModifyOrder(ctx context.Context, order models.Order, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyOrder", ctx, order, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyOrder indicates an expected call of ModifyOrder.
func (mr *MockStorageMockRecorder) ModifyOrder(ctx, order, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyOrder", reflect.TypeOf((*MockStorage)(nil).ModifyOrder), ctx, order, tx)
}

// UpdateBalance mocks base method.
func (m *MockStorage) UpdateBalance(ctx context.Context, userID string, amount *float64, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, userID, amount, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockStorageMockRecorder) UpdateBalance(ctx, userID, amount, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockStorage)(nil).UpdateBalance), ctx, userID, amount, tx)
}

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// FetchBalanceByUserID mocks base method.
func (m *MockReader) FetchBalanceByUserID(ctx context.Context, userID string) (models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBalanceByUserID", ctx, userID)
	ret0, _ := ret[0].(models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchBalanceByUserID indicates an expected call of FetchBalanceByUserID.
func (mr *MockReaderMockRecorder) FetchBalanceByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBalanceByUserID", reflect.TypeOf((*MockReader)(nil).FetchBalanceByUserID), ctx, userID)
}

// FetchCurrentBalance mocks base method.
func (m *MockReader) FetchCurrentBalance(ctx context.Context, userID string, tx *sqlx.Tx) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCurrentBalance", ctx, userID, tx)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCurrentBalance indicates an expected call of FetchCurrentBalance.
func (mr *MockReaderMockRecorder) FetchCurrentBalance(ctx, userID, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCurrentBalance", reflect.TypeOf((*MockReader)(nil).FetchCurrentBalance), ctx, userID, tx)
}

// FetchOrdersByUserID mocks base method.
func (m *MockReader) FetchOrdersByUserID(ctx context.Context, userID string) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOrdersByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOrdersByUserID indicates an expected call of FetchOrdersByUserID.
func (mr *MockReaderMockRecorder) FetchOrdersByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOrdersByUserID", reflect.TypeOf((*MockReader)(nil).FetchOrdersByUserID), ctx, userID)
}

// FetchPendingOrders mocks base method.
func (m *MockReader) FetchPendingOrders(ctx context.Context) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPendingOrders", ctx)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPendingOrders indicates an expected call of FetchPendingOrders.
func (mr *MockReaderMockRecorder) FetchPendingOrders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPendingOrders", reflect.TypeOf((*MockReader)(nil).FetchPendingOrders), ctx)
}

// FetchWithdrawalsByUserID mocks base method.
func (m *MockReader) FetchWithdrawalsByUserID(ctx context.Context, userID string) ([]models.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWithdrawalsByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWithdrawalsByUserID indicates an expected call of FetchWithdrawalsByUserID.
func (mr *MockReaderMockRecorder) FetchWithdrawalsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWithdrawalsByUserID", reflect.TypeOf((*MockReader)(nil).FetchWithdrawalsByUserID), ctx, userID)
}

// FindUserByLogin mocks base method.
func (m *MockReader) FindUserByLogin(ctx context.Context, user models.User) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByLogin", ctx, user)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByLogin indicates an expected call of FindUserByLogin.
func (mr *MockReaderMockRecorder) FindUserByLogin(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByLogin", reflect.TypeOf((*MockReader)(nil).FindUserByLogin), ctx, user)
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockWriter) CreateOrder(ctx context.Context, order models.Order, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, order, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockWriterMockRecorder) CreateOrder(ctx, order, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockWriter)(nil).CreateOrder), ctx, order, tx)
}

// CreateUser mocks base method.
func (m *MockWriter) CreateUser(ctx context.Context, user models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockWriterMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockWriter)(nil).CreateUser), ctx, user)
}

// CreateWithdrawal mocks base method.
func (m *MockWriter) CreateWithdrawal(ctx context.Context, withdrawal models.Withdrawal, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawal", ctx, withdrawal, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithdrawal indicates an expected call of CreateWithdrawal.
func (mr *MockWriterMockRecorder) CreateWithdrawal(ctx, withdrawal, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawal", reflect.TypeOf((*MockWriter)(nil).CreateWithdrawal), ctx, withdrawal, tx)
}

// IncreaseWithdrawnAmount mocks base method.
func (m *MockWriter) IncreaseWithdrawnAmount(ctx context.Context, userID string, amount float64, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseWithdrawnAmount", ctx, userID, amount, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseWithdrawnAmount indicates an expected call of IncreaseWithdrawnAmount.
func (mr *MockWriterMockRecorder) IncreaseWithdrawnAmount(ctx, userID, amount, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseWithdrawnAmount", reflect.TypeOf((*MockWriter)(nil).IncreaseWithdrawnAmount), ctx, userID, amount, tx)
}

// ModifyOrder mocks base method.
func (m *MockWriter) ModifyOrder(ctx context.Context, order models.Order, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyOrder", ctx, order, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyOrder indicates an expected call of ModifyOrder.
func (mr *MockWriterMockRecorder) ModifyOrder(ctx, order, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyOrder", reflect.TypeOf((*MockWriter)(nil).ModifyOrder), ctx, order, tx)
}

// UpdateBalance mocks base method.
func (m *MockWriter) UpdateBalance(ctx context.Context, userID string, amount *float64, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, userID, amount, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockWriterMockRecorder) UpdateBalance(ctx, userID, amount, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockWriter)(nil).UpdateBalance), ctx, userID, amount, tx)
}
